variables:
  CONTAINER_IMAGE_NAME: ${CI_REGISTRY}/${I_PROJECT_NAMESPACE}/{CI_PROJECT_NAME}

image: docker:latest

services:
- docker:dind

before_script:
- docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}

release:
  stage: build
  variables:
    R_VERSION: 3.3.1
  script:
  - docker build --pull -t ${CONTAINER_IMAGE_NAME}:release --build-arg R_VERSION=${R_VERSION} release
  - docker tag ${CONTAINER_IMAGE_NAME}:release ${CONTAINER_IMAGE_NAME}:${R_VERSION}
  - docker tag ${CONTAINER_IMAGE_NAME}:release ${CONTAINER_IMAGE_NAME}:latest
  - docker run ${CONTAINER_IMAGE_NAME}:release R --version
  - docker push ${CONTAINER_IMAGE_NAME}:release
  - docker push ${CONTAINER_IMAGE_NAME}:${R_VERSION}
  - docker push ${CONTAINER_IMAGE_NAME}:latest

devel:
  stage: build
  script:
  - docker build --pull -t ${CONTAINER_IMAGE_NAME}:devel devel
  - docker run ${CONTAINER_IMAGE_NAME}:devel R --version
  - docker push ${CONTAINER_IMAGE_NAME}:devel

patched:
  stage: build
  script:
  - docker build --pull -t ${CONTAINER_IMAGE_NAME}:patched patched
  - docker run ${CONTAINER_IMAGE_NAME}:patched R --version
  - docker push ${CONTAINER_IMAGE_NAME}:patched
