image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

release:
  stage: build
  script:
    - docker build --pull -t artemklevtsov/r-alpine:release -t artemklevtsov/r-alpine:latest release
    - docker run -ti artemklevtsov/r-alpine:release R --version
    - docker push artemklevtsov/r-alpine:release
    - docker push artemklevtsov/r-alpine:latest

devel:
  stage: build
  script:
    - docker build --pull -t artemklevtsov/r-alpine:devel devel
    - docker run -ti artemklevtsov/r-alpine:devel R --version
    - docker push artemklevtsov/r-alpine:devel
