image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

release:
  stage: build
  variables:
    VERSION: 3.3.1
  script:
    - docker build --pull -t artemklevtsov/r-alpine:release release
    - docker tag artemklevtsov/r-alpine:release artemklevtsov/r-alpine:latest
    - docker tag artemklevtsov/r-alpine:release artemklevtsov/r-alpine:${VERSION}
    - docker run artemklevtsov/r-alpine:release R --version
    - docker push artemklevtsov/r-alpine:release
    - docker push artemklevtsov/r-alpine:latest
    - docker push artemklevtsov/r-alpine:${VERSION}

devel:
  stage: build
  script:
    - docker build --pull -t artemklevtsov/r-alpine:devel devel
    - docker run artemklevtsov/r-alpine:devel R --version
    - docker push artemklevtsov/r-alpine:devel

patched:
  stage: build
  script:
    - docker build --pull -t artemklevtsov/r-alpine:patched patched
    - docker run artemklevtsov/r-alpine:patched R --version
    - docker push artemklevtsov/r-alpine:patched
