image: docker:latest

services:
- docker:dind

before_script:
- docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}

release:
  stage: build
  variables:
    R_VERSION: 3.3.1
  script:
  - docker build --pull -t ${CI_REGISTRY_IMAGE}:release --build-arg R_VERSION=${R_VERSION} release
  - docker tag ${CI_REGISTRY_IMAGE}:release ${CI_REGISTRY_IMAGE}:${R_VERSION}
  - docker tag ${CI_REGISTRY_IMAGE}:release ${CI_REGISTRY_IMAGE}:latest
  - docker run ${CI_REGISTRY_IMAGE}:release R --version
  - docker push ${CI_REGISTRY_IMAGE}:release
  - docker push ${CI_REGISTRY_IMAGE}:${R_VERSION}
  - docker push ${CI_REGISTRY_IMAGE}:latest

devel:
  stage: build
  script:
  - docker build --pull -t ${CI_REGISTRY_IMAGE}:devel devel
  - docker run ${CI_REGISTRY_IMAGE}:devel R --version
  - docker push ${CI_REGISTRY_IMAGE}:devel

patched:
  stage: build
  script:
  - docker build --pull -t ${CI_REGISTRY_IMAGE}:patched patched
  - docker run ${CI_REGISTRY_IMAGE}:patched R --version
  - docker push ${CI_REGISTRY_IMAGE}:patched

trigger:benchr:
  type: deploy
  images: alpine:latest
  script:
  - apk --no-cache add curl
  - "curl -X POST -F token=${BENCHR_TOKEN} -F ref=docker https://gitlab.com/api/v3/projects/1284608/trigger/builds"
