image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" docker.io

release:
  stage: build
  variables:
    R_VERSION: 3.3.1
  script:
    - docker build --pull -t artemklevtsov/r-alpine:release --build-arg R_VERSION=${R_VERSION} release
    - docker tag artemklevtsov/r-alpine:release artemklevtsov/r-alpine:${R_VERSION}
    - docker tag artemklevtsov/r-alpine:release artemklevtsov/r-alpine:latest
    - docker run artemklevtsov/r-alpine:release R --version
    - docker push artemklevtsov/r-alpine:release
    - docker push artemklevtsov/r-alpine:${R_VERSION}
    - docker push artemklevtsov/r-alpine:latest

devel:
  stage: build
  script:
    - docker build --pull -t artemklevtsov/r-alpine:devel devel
    - docker run artemklevtsov/r-alpine:devel R --version
    - docker push artemklevtsov/r-alpine:devel

patched:
  stage: build
  script:
    - docker build --pull -t artemklevtsov/r-alpine:patched patched
    - docker run artemklevtsov/r-alpine:patched R --version
    - docker push artemklevtsov/r-alpine:patched
