image: docker:latest

services:
  - docker:dind

stages:
  - build-base
  - build-others
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}

gcc-release:
  stage: build-base
  variables:
    R_VERSION: 3.3.3
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE} --build-arg R_VERSION=${R_VERSION} ${CI_BUILD_NAME%-*}/${CI_BUILD_NAME#*-}
    - docker tag ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME#*-}
    - docker tag ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_IMAGE}:${R_VERSION}
    - docker tag ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_IMAGE}:${R_VERSION:0:1}
    - docker tag ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*}
    - docker tag ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME}
    - docker tag ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*}-${R_VERSION}
    - docker tag ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*}-${R_VERSION:0:1}
    - docker run ${CI_REGISTRY_IMAGE} R --version
    - docker push ${CI_REGISTRY_IMAGE}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME#*-}
    - docker push ${CI_REGISTRY_IMAGE}:${R_VERSION}
    - docker push ${CI_REGISTRY_IMAGE}:${R_VERSION:0:1}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*}-${R_VERSION}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*}-${R_VERSION:0:1}

gcc-devel:
  stage: build-base
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} ${CI_BUILD_NAME%-*}/${CI_BUILD_NAME#*-}
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME#*-}
    - docker run ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} R --version
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME#*-}

gcc-patched:
  stage: build-base
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} ${CI_BUILD_NAME%-*}/${CI_BUILD_NAME#*-}
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME#*-}
    - docker run ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} R --version
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME#*-}

clang-release:
  stage: build-base
  variables:
    R_VERSION: 3.3.3
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*} --build-arg R_VERSION=${R_VERSION} ${CI_BUILD_NAME%-*}/${CI_BUILD_NAME#*-}
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*} ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME}
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*} ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*}-${R_VERSION}
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*} ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*}-${R_VERSION:0:1}
    - docker run ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*} R --version
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*}-${R_VERSION}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME%-*}-${R_VERSION:0:1}

clang-devel:
  stage: build-base
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} ${CI_BUILD_NAME%-*}/${CI_BUILD_NAME#*-}
    - docker run ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} R --version
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME}

clang-patched:
  stage: build-base
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} ${CI_BUILD_NAME%-*}/${CI_BUILD_NAME#*-}
    - docker run ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} R --version
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME}

pkg-dev:
  stage: build-others
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} ${CI_BUILD_NAME}
    - docker run ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} Rscript -e 'packageVersion("devtools")'
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME}

tidyverse:
  stage: build-others
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} ${CI_BUILD_NAME}
    - docker run ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME} Rscript -e 'packageVersion("tidyverse")'
    - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_NAME}

triggers:
  type: deploy
  image: alpine:latest
  before_script:
    - apk --no-cache add curl
  script:
    - "curl -X POST -F token=${BENCHR_TOKEN} -F ref=docker https://gitlab.com/api/v3/projects/1284608/trigger/builds"
