image: docker:latest

services:
  - docker:dind

stages:
  - build-base
  - build-others
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}

r-release:
  stage: build-base
  variables:
    R_VERSION: 3.4.1
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_BUILD_NAME}
  script:
    - docker build --pull --cache-from ${IMAGE_NAME} -t ${IMAGE_NAME} --build-arg R_VERSION=${R_VERSION} gcc/release
    - docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${R_VERSION}
    - docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${R_VERSION:0:1}
    - docker run ${IMAGE_NAME} R --version
    - docker push ${CI_REGISTRY_IMAGE}
    - docker push ${CI_REGISTRY_IMAGE}:${R_VERSION}
    - docker push ${CI_REGISTRY_IMAGE}:${R_VERSION:0:1}

r-devel:
  stage: build-base
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_BUILD_NAME}
  script:
    - docker build --pull --cache-from ${IMAGE_NAME} -t ${IMAGE_NAME} gcc/devel
    - docker run ${IMAGE_NAME} R --version
    - docker push ${IMAGE_NAME}

r-patched:
  stage: build-base
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_BUILD_NAME}
  script:
    - docker build --pull --cache-from ${IMAGE_NAME} -t ${IMAGE_NAME} gcc/patched
    - docker run ${IMAGE_NAME} R --version
    - docker push ${IMAGE_NAME}

tidyverse:
  stage: build-others
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_BUILD_NAME}
  script:
    - docker build --pull --cache-from ${IMAGE_NAME} -t ${IMAGE_NAME} gcc/devel
    - docker run ${IMAGE_NAME} Rscript -e 'packageVersion("tidyverse")'
    - docker push ${IMAGE_NAME}
